.\" Manpage for prostudy.
.\" Contact julie@windelborg.dk to correct errors or typos.
.TH man 8 "01 Nov 2018" "1.0" "prostudy man page"
.SH NAME
prostudy \- Be more focused when you study.
.SH SYNOPSIS
prostudy [NUMBER]
.SH DESCRIPTION
Pro Study is available to help you block distractions while you study. It works by blocking based on 3 levels: domain blocking based on hostfile, ip blocking based on iptables, and process blocking run by grapping and killing pids of applications you are not allowed to get distracted by.
.SH OPTIONS
See prostudy --help
.br
The options will be described better here at another time.
.SH SEE ALSO
hosts(5), iptables(8), pgrep(1)
.SH BUGS
Just fix them and send me a pull request.
.SH AUTHOR
Julie Windelborg Nielsen (julie@windelborg.dk)
